### ISSUE TITLE
Getting Error When Setting Target Temperature

### ISSUE THREAD

**Issue by EricShell** [bdraco/nexia#34]
When I try to change the temperature in Home Assistant, I get the following error, which appears to be coming from the nexia API itself:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 202, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 207, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 613, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/nexia/climate.py", line 340, in async_set_temperature
    await self._zone.set_heat_cool_temp(
  File "/usr/local/lib/python3.10/site-packages/nexia/zone.py", line 340, in set_heat_cool_temp
    heat_temperature = min(
TypeError: '<' not supported between instances of 'int' and 'NoneType'

I am running the newest version of home assistant (2022.10.5), with version 2.0.4 of the nexia API. I have a XL850 thermostat for my system, and am trying to set the temperature with the system in Heating or Cooling mode.

**Comment by k5njm** [comment]
Also reported here: https://github.com/home-assistant/core/issues/80988

**Comment by LokilloMM** [comment]
TRied adjusting temp and I got Failed to call service climate/set_temperature. '<' not supported between instances of 'int' and 'NoneType' on all 3 thermostats
